#!/bin/sh

FILENAME=test.fat32

case "$1" in
	'make')
		#rm -rf test.fat32
		if [ ! -f $FILENAME ]; then
			echo "Creating $FILENAME"
			dd if=/dev/zero of=$FILENAME bs=1M count=64
		fi
		ls -lah $FILENAME
		echo "Formatting $FILENAME with FAT32"
		/sbin/mkfs.fat -v -s1 -F32 -n MACHINA $FILENAME
		chmod a+rw $FILENAME
		echo "Done."
		;;
	'mount')
		#rm -rf fs
		mkdir -p ./fs && sudo mount -o loop -tvfat test.fat32 ./fs 
		;;
	'unmount')
		sudo umount ./fs
		echo 'continuing'
		;;
	'populate')
		cd fs
		echo "Medium sized filename on this one." > thisisamidsizefilename.txt
		mkdir subdir
		echo "This is file A" > a.txt
		echo "This is file B" > b.txt
		echo "This is a long filename!" > subdir/this\ is\ a\ super\ long\ filename\ with\ spaces.txt
		echo "Hello, World" > subdir/c.txt
		;;
	*)
		echo "usage $0 make|mount|unmount|populate" ;;
esac
