#!/bin/sh

FILENAME=test.fat32

case "$1" in
	'make')
		#rm -rf test.fat32
		if [ ! -f $FILENAME ]; then
			echo "Creating $FILENAME"
			dd if=/dev/zero of=$FILENAME bs=1M count=64
		fi
		ls -lah $FILENAME
		echo "Formatting $FILENAME with FAT32"
		/sbin/mkfs.fat -v -s1 -F32 -n MACHINA $FILENAME
		chmod a+rw $FILENAME
		echo "Done."
		;;
	'mount')
		#rm -rf fs
		mkdir -p ./fs && sudo mount -o loop -tvfat test.fat32 ./fs 
		;;
	'unmount')
		sudo umount ./fs
		echo 'continuing'
		;;
	'populate')
		$0 mount && sudo cp -r --copy-contents -L /etc/systemd/ ./fs/ && $0 unmount
		;;
	*)
		echo "usage $0 make|mount|unmount|populate" ;;
esac

exit 0
